# Generated by Django 4.2.3 on 2023-08-20 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appName', '0002_alter_news_options_alter_news_photo_alter_news_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='news_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='appName.category'),
        ),
    ]
